### ISSUE TITLE
11

### ISSUE THREAD

**Issue by carl1218** [at-wat/hokuyo3d#4]
`<launch>

  <node name="hokuyo_node" pkg="hokuyo_node" type="hokuyo_node">
    <param name="port" type="string" value="/dev/ttyACM0"/>
    <param name="min_ang" value="-1.7" />
    <param name="max_ang" value="1.7" />
    <param name="min_range" value="0.18" />
    <param name="hokuyo_node/calibrate_time" value="true" />
    <param name="tracking_frame" type="string" value="laser_link" />
    <remap from="scan" to="/laser_scan"/>
  </node>

  <node name="cartographer_node" pkg="cartographer_ros"
      type="cartographer_node" args="
          -configuration_directory $(find cartographer_ros)/configuration_files
          -configuration_basename hokuyo.lua"
      output="screen">
    <remap from="scan" to="/laser_scan" />
  </node>
- </launch>`

**Comment by at-wat** [comment]
??
