### ISSUE TITLE
Available SLAM algorithm

### ISSUE THREAD

**Issue by ArthurYu96** [at-wat/hokuyo3d#7]
Hi, thank you for all your works and the driver works really well. I'm now use HOKUYO YVT-X002 laser to realize 3D SLAM, but i found that most of the SLAM algorithms don't work well on hokuyo 3d laser. So could you provide me an available algorithm for hokuyo 3d laser? Thanks for any response.

**Comment by at-wat** [comment]
One of the best available slam solutions, for now, is google cartographer.
I used the cartographer with two YVT-X002 on our robot system.

In my opinion, YVT-X002 data can be slammed by the cartographer without odometry. However, it needs tuning of the parameters, including still undocumented ones.
(The default parameters of the cartographer is tuned for Velodyne.)

**Comment by at-wat** [comment]
@ArthurYu96 I have released Google Cartographer configuration package for single HOKUYO YVT LIDAR.
https://github.com/at-wat/cartographer_hokuyo3d

If you have any question on this SLAM configuration, please open an issue on at-wat/cartographer_hokuyo3d repository.
